/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Hospital.Doctor;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author Surbhi
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Doctor doctor;
    EcoSystem ecoSystem;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, Doctor doctor, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.doctor = doctor;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewPatients = new javax.swing.JButton();
        btnRaiseEquipment = new javax.swing.JButton();
        btnDemandHistory = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle.setText("Doctor Work Area ");

        btnViewPatients.setText("View Patients");
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });

        btnRaiseEquipment.setText("Raise Equipment");
        btnRaiseEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseEquipmentActionPerformed(evt);
            }
        });

        btnDemandHistory.setText("Demand History");
        btnDemandHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemandHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnViewPatients)
                        .addGap(18, 18, 18)
                        .addComponent(btnRaiseEquipment)
                        .addGap(18, 18, 18)
                        .addComponent(btnDemandHistory)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPatients)
                    .addComponent(btnRaiseEquipment)
                    .addComponent(btnDemandHistory))
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
        // TODO add your handling code here: 
        ViewPatientsJPanel vpjp = new ViewPatientsJPanel(userProcessContainer, doctor, ecoSystem);
        userProcessContainer.add("ViewPatientsJPanel",vpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnRaiseEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseEquipmentActionPerformed
        // TODO add your handling code here:
        RaiseEquipmentsJPanel rejp = new RaiseEquipmentsJPanel(userProcessContainer, doctor, ecoSystem);
        userProcessContainer.add("RaiseEquipmentsJPanel",rejp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnRaiseEquipmentActionPerformed

    private void btnDemandHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemandHistoryActionPerformed
        // TODO add your handling code here:
        DemandHistoryJPanel dhjp = new DemandHistoryJPanel(userProcessContainer, doctor, ecoSystem);
        userProcessContainer.add("DemandHistoryJPanel",dhjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);      
    }//GEN-LAST:event_btnDemandHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemandHistory;
    private javax.swing.JButton btnRaiseEquipment;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
