/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistRole;

import Business.EcoSystem;
import Business.Hospital.Receptionist;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Surbhi
 */
public class UpdatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePatientJPanel
     */
    JPanel userProcessContainer;
    Receptionist receptionist;
    EcoSystem ecoSystem;
    public UpdatePatientJPanel(JPanel userProcessContainer, Receptionist receptionist, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.receptionist = receptionist;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAssignedDoc = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblEmergencyContact = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtAssignedDoc = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        txtEmergencyContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblFName.setForeground(new java.awt.Color(252, 92, 59));
        lblFName.setText("First Name: ");
        add(lblFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 88, 134, -1));

        lblLName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLName.setForeground(new java.awt.Color(252, 92, 59));
        lblLName.setText("Last Name: ");
        add(lblLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 122, 134, -1));

        lblDOB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(252, 92, 59));
        lblDOB.setText("DOB:");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 164, 134, -1));

        lblPhoneNumber.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(252, 92, 59));
        lblPhoneNumber.setText("Phone Number: ");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 202, 134, -1));

        lblAssignedDoc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblAssignedDoc.setForeground(new java.awt.Color(252, 92, 59));
        lblAssignedDoc.setText("Assigned Doctor: ");
        add(lblAssignedDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 240, 134, -1));

        lblAddress.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(252, 92, 59));
        lblAddress.setText("Address: ");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 274, 134, -1));

        lblEmailID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblEmailID.setForeground(new java.awt.Color(252, 92, 59));
        lblEmailID.setText("Email Id: ");
        add(lblEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 370, 136, -1));

        lblEmergencyContact.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblEmergencyContact.setForeground(new java.awt.Color(252, 92, 59));
        lblEmergencyContact.setText("Emergency Contact: ");
        add(lblEmergencyContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 412, -1, -1));
        add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 84, 244, -1));
        add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 122, 244, -1));
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 160, 244, -1));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 198, 244, -1));
        add(txtAssignedDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 236, 244, -1));
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 242, -1));
        add(txtEmergencyContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 408, 238, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 274, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 19, -1, -1));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 490, -1, -1));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Patients");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 198, 27));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        ReceptionistWorkAreaJPanel rwajp = new ReceptionistWorkAreaJPanel
        (userProcessContainer, receptionist, ecoSystem);     
        userProcessContainer.add("ReceptionistWorkAreaJPanel",rwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAssignedDoc;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblEmergencyContact;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAssignedDoc;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtEmergencyContact;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
