/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalInventoryManagerRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Surbhi
 */
public class InventoryManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    public InventoryManagerWorkAreaJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAcceptDemand = new javax.swing.JButton();
        btnDeclineDemand = new javax.swing.JButton();
        btnChooseSupplier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDemandQueue = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 92, 59));
        jLabel1.setText("Hospital Inventory Manager Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 21, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        btnAcceptDemand.setText("Accept Demand");
        add(btnAcceptDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btnDeclineDemand.setText("Decline Demand");
        add(btnDeclineDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        btnChooseSupplier.setText("Choose Supplier");
        btnChooseSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSupplierActionPerformed(evt);
            }
        });
        add(btnChooseSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        tblDemandQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Urgency", "Doctor Name", "Status", "Additional Message"
            }
        ));
        jScrollPane2.setViewportView(tblDemandQueue);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 610, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChooseSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSupplierActionPerformed
        // TODO add your handling code here:
        ChooseSupplierJPanel rwajp = new ChooseSupplierJPanel
        (userProcessContainer);
        userProcessContainer.add("ReceptionistWorkAreaJPanel",rwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
    }//GEN-LAST:event_btnChooseSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptDemand;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChooseSupplier;
    private javax.swing.JButton btnDeclineDemand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDemandQueue;
    // End of variables declaration//GEN-END:variables
}
