/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.pharmacyUnit;

import javax.swing.JPanel;

/**
 *
 * @author swaroopgupta
 */
public class AddNewProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddNewProduct
     */
    JPanel userProcessContainer;
    public AddNewProduct(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        nameJTextField1 = new javax.swing.JTextField();
        nameJTextField2 = new javax.swing.JTextField();
        nameJTextField3 = new javax.swing.JTextField();
        addMedBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("New Product");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 260, 30));

        lblTitle1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle1.setText("Product Name");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 30));

        lblTitle2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle2.setText("Product Price");
        add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 30));

        lblTitle3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle3.setText("Product Qty");
        add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 90, 30));

        lblTitle4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle4.setText("Product Type");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, 30));

        nameJTextField.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 296, -1));

        nameJTextField1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField1.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 296, -1));

        nameJTextField2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField2.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 296, -1));

        nameJTextField3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField3.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 296, -1));

        addMedBtn.setBackground(new java.awt.Color(37, 116, 187));
        addMedBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        addMedBtn.setText("Add");
        addMedBtn.setPreferredSize(new java.awt.Dimension(156, 43));
        addMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedBtnActionPerformed(evt);
            }
        });
        add(addMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedBtnActionPerformed
        
    }//GEN-LAST:event_addMedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedBtn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTextField nameJTextField2;
    private javax.swing.JTextField nameJTextField3;
    // End of variables declaration//GEN-END:variables
}
