/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.pharmacyUnit;

import Business.Products.Product;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author swaroopgupta
 */
public class ManageProductCatalog extends javax.swing.JPanel {

    /**
     * Creates new form AddNewProduct
     */
    JPanel userProcessContainer;
    List<Product> productList;
    Product selectedProduct;
    
    public ManageProductCatalog(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        nameJTextField1 = new javax.swing.JTextField();
        nameJTextField2 = new javax.swing.JTextField();
        nameJTextField3 = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductJTable = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add/Modify/Remove Products");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 310, 30));

        lblTitle1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle1.setText("Product Name");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 100, 30));

        lblTitle2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle2.setText("Product Price");
        add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 90, 30));

        lblTitle3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle3.setText("Product Qty");
        add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 90, 30));

        lblTitle4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(252, 92, 59));
        lblTitle4.setText("Product Type");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 100, 30));

        nameJTextField.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 170, -1));

        nameJTextField1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField1.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 170, -1));

        nameJTextField2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField2.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 170, -1));

        nameJTextField3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        nameJTextField3.setForeground(new java.awt.Color(25, 56, 82));
        add(nameJTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 170, -1));

        btnRemove.setBackground(new java.awt.Color(37, 116, 187));
        btnRemove.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRemove.setText("Remove Product");
        btnRemove.setPreferredSize(new java.awt.Dimension(156, 43));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        ProductJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ProductJTable.setForeground(new java.awt.Color(25, 56, 82));
        ProductJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Type", "Price", "Qty Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(ProductJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 567, 91));

        btnUpdate.setBackground(new java.awt.Color(37, 116, 187));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnUpdate.setText("Update Product");
        btnUpdate.setPreferredSize(new java.awt.Dimension(156, 43));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        btnSave.setBackground(new java.awt.Color(37, 116, 187));
        btnSave.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnSave.setText("Save ");
        btnSave.setPreferredSize(new java.awt.Dimension(156, 43));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductJTable;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTextField nameJTextField2;
    private javax.swing.JTextField nameJTextField3;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
//       ProductJTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) ProductJTable.getModel();
        model.setRowCount(0);
        
        for(Product p : productList){
            Object[] row = new Object[model.getColumnCount()];
            row[0] = p.getName();
            row[0] = p.getType();
            row[0] = p.getPrice();
            row[0] = p.getQty();
            model.addRow(row);
        }
    }
}
